### ISSUE TITLE
implement map/reduce

### ISSUE THREAD

**Issue by wiso** [bluehood/tdataframe#10]
Hello, I think it would be nice to have a sort of map/reduce workflow.

`map` is similar to your `foreach` but returns values, for example as

    d.map([](double b1, double b2) { return b1 * b2; }, {"b1", "b2"});

I don't know if you prefer something based on iterators as `std::transform`, probably it is not the best if you want to chain operations.

At the same time:

    double sum_b1 = d.reduce([](double x, double y) { return x + y; }, {"b1"}, 0.);

Probably to save memory for the output of the `map` you can also implement:

    double sum_b1xb2 = d.map_reduce([](double b1, double b2) { return b1 * b2; },
                                    [](double x, double y) { return x + y; }, {"b1", "b2"}, 0.);

or maybe implement everything in a smart way: first create expressions and the evaluate:

    auto expression_b1xb2 = d.map([](double b1, double b2) { return b1 * b2; }, {"b1", "b2"});
    double sum_b1xb2 = expression_b1xb2.reduce(](double x, double y) { return x + y; }, {"b1", "b2"}, 0.).eval()

I think your project is going in the direction of creating computational graph, for example have a look to http://dask.pydata.org/ or spark. Maybe it is easier to interface the ROOT TTree format with existing tools.

**Comment by eguiraud** [comment]
Hello,
thank you for your feedback! This is definitely a discussion that should be had.

First off, for completeness, let me point out that ROOT has quite generic, parallel `Map`, `Reduce`, and `MapReduce` in `TProcessExecutor` and `TThreadExecutor`. But you cannot weave this calls into a functional chain, so this is probably not what you are looking for.

Secondly, I will take advantage of this thread to make clear that what this project is going for is not a generic data stream processing framework. This is just a (much) nicer way to loop over trees, with built-in and transparent optimizations, and a more flexible `TTree::Draw`. It is tailored to the workflow of hep scientists, which is both a strength (we will have better and better ways to fill histograms with actions, nicer and nicer ways to express parallelism, caching, and of course we have complete integration with ROOT) and a limitation (for instance, we only allow a series of filters and then a single action, no other combination). I think we are already tackling some important problems as is.

But! Let's pretend I didn't say anything. What would you want `Map` to do in this particular context?
```c++
dataframe.filter(f1, b1).filter(f2,b2).map(square, {"pt_x"}).foreach(...);
```
Are you sure most ROOT users would not prefer, for instance, an optional "pre-processing" lambda that you can pass to the `fillhist` to perform some transformation on the branches before calling `Fill` (a'-la `TTree::Draw`)?

**Comment by eguiraud** [comment]
I decided to implement `AddBranch` instead. It provides a way to store a per-entry calculation and use it in subsequent calls as if it was a tree branch. `AddBranch` introduces the concept of temporary branches, created on-the-fly on a per-entry basis.

Example:
```c++
TDataFrame d("mytree", myfile);
auto d_with_myvar = d.AddBranch("myvar", expensiveComputation, {"var1", "var2", "var3"});
auto h1 = d.Filter(cut1, {"myvar"}).Histo("myvar");
auto h2 = d.Filter(cut2, {"myvar"}).Histo("myvar");
h1->Draw();
h2->Draw("SAME");
```
