### ISSUE TITLE
add pre-processing lambda to `Histo` action

### ISSUE THREAD

**Issue by eguiraud** [bluehood/tdataframe#18]
Let's say I want to fill a histogram with the square of a variable, or with the some of other two.
It would be nice to be able to do it like this:
```c++
auto square = [](double x) { return x*x; };
d.Histo(square, {"var1"});
```
and like this:
```c++
d.Histo([](double x, double y) { return x + y; }, {"var1", "var2"});
```

**Comment by dpiparo** [comment]
Hi Enrico,

isn't this functionality absorbed by the creation of a branch?

D

**Comment by eguiraud** [comment]
Yes, one could do
```c++
d.Filter(...).AddBranch("x2", square, {"x"}).Histo("x2")
```
but I would not exclude the shortcut
```c++
d.Filter(...).Histo("x", square)
```

It's probably not a top priority though.

**Comment by dpiparo** [comment]
I agree it's a nice idea and all the pieces are there so why not!As you say priority is not high but on the other hand it's quite quick to implement too so it could be done whenever we want :)

**Comment by eguiraud** [comment]
On a second thought, we can do better than a pre-processing lambda. It would be nice to have something like this:
```c++
// 1. pre-processing lambda
d.Histo("particle", [](Particle& p) { return p.Pt(); });
// 2. pre-processing method
d.Histo("particle", &Particle::Pt); 
// 3. pre-processing method on a collection
d.Histo("part_vec", &std::vector<Particle>::size);
// 4. pre-processing method on elements of a collection
d.Histo("part_vec", &Particle::Pt);
```
If the result of the pre-processing is a container we fill with all elements of the container, like we do now.
Application does not have to be limited to `Histo` by the way.

**Comment by eguiraud** [comment]
Nice, but since one can already achieve the same with a Define + Histo, this is likely never going to happen
