### ISSUE TITLE
Improve the Histo action for what concerns the signature foreseeing the passing of an histogram

### ISSUE THREAD

**Issue by dpiparo** [bluehood/tdataframe#32]
Currently, the model is used to construct the new histogram which is returned wrapped in a TActionResultPtr and is left untouched.
- option 1: `Histo(string branch, TH1& model)`  it is possible to access the histogram without triggering TDataFrame::Run but if it is not triggered, the model will be empty or in the state in which it was passed to the method. The histogram is packed into a TActionResultPtr and the reference counting is artificially incremented to leave ownership to the user.
- option 2: `Histo(string branch, TH1&& tofill)`  users have to use std::move to pass a non-temporary TH1 . This makes the interface contract clear but imposes a std::move, an obligation absent in the entire set of ROOT6 interfaces.

**Comment by eguiraud** [comment]
My opinion on this is that option 1 leaves the interface prone to usage errors and misunderstandings.

I would rather have the interface explicitly state that the histogram passed to `Histo` is "lost" and only recoverable through the smart pointer it returns. Code will not compile if users do not acknowledge this fact through usage of `std::move`. Worst case scenario with option 2 is that users have to look at one example to find out about move semantics; I am not even sure it's a con actually :P

**Comment by eguiraud** [comment]
done in ROOT
