### ISSUE TITLE
Coding Conventions

### ISSUE THREAD

**Issue by dpiparo** [bluehood/tdataframe#33]
ROOT coding conventions shall be respected:
- ROOT coding conventions are to be followed unaltered (no exceptions for TActionResultPtr for example, even if it looks like a shared ptr)
- Use the clang-format profile to format the code (https://root.cern/coding-conventions#ClangFormat)
- Properly reshuffle routines, helpers and classes in the ROOT, ROOT::Bits(?) and ROOT::Internal namespaces
- Doxygen documentation!
- In first approximation the single header solution can be kept

**Comment by eguiraud** [comment]
all done except for the doxygen documentation.
documentation would deserve a whole new issue though.
