### ISSUE TITLE
Engineer a general way to smartly loop over collections

### ISSUE THREAD

**Issue by dpiparo** [bluehood/tdataframe#34]
TTreeFormula is appreciated also because it allows to easily loop over collections in an implicit manner. For example for histogramming the DeltaR between all muons and all jets in an event.
TDataFrame shall provide a similar way to approach this kind of problems, but in a very general manner.
Ideas could involve passing a lambda taking as input parameters types T and V and then apply it to two branches of type COLL1<T> and COLL2<V>.

**Comment by eguiraud** [comment]
I think this is a very important issue that must be tackled at some point soon.
Some more brainstorming and whiteboarding is needed to come up with an intuitive way to let users express loops over collections implicitly that fits with the rest of the interface.

**Comment by eguiraud** [comment]
Being addressed at https://sft.its.cern.ch/jira/browse/ROOT-8865.
Closing here.
