### ISSUE TITLE
Re-implement parallelisation of data processing with the percolation of a slot index (usage of a workspace)

### ISSUE THREAD

**Issue by dpiparo** [bluehood/tdataframe#36]
Parallelisation can be implemented in several ways. Among the most efficient ones, one can re-elaborate the previous prototype of TDataFrame which considered the usage of TTreeProcessor::Process and enhance it percolating a slot index to all lambdas acting on entries.
This implies:
- Making all the TTreeReaderValues "slot-local"
- Making all the states of the filters "slot-local"
- Making all the action results, or pointee thereof "slot-local"
- When Dump is implemented, the usage of Parallel Buffer Merge to write from different threads simultaneously on the same tree.

In order to deal with these states, no resource protection mechanism shall be considered (atomic, thread_local, mutexes) but rather an n-uplication of values merged/finalised after the end of the processing. In this respect, as far as Action Results are involved, the TThreadedObject can become handy.

**Comment by eguiraud** [comment]
The state of `TDataFrameBranch` must be made "slot-local" as well.

I would not cross out different ways to implement a parallel `Dump` action than Parallel Buffer Merge, I think an in-depth discussion is required.

**Comment by eguiraud** [comment]
done in master
