### ISSUE TITLE
Snapshot action

### ISSUE THREAD

**Issue by dpiparo** [bluehood/tdataframe#37]
In order to checkpoint the processing, one can imagine to "Dump" the data the TDataFrame is "viewing" on a physical file in the form of a TTree.
```c++
auto myHisto = myFrame
   .Filter(myFilter1,myBranchList1)
   .AddBranch("myNewBranch",myNewBranchCreator, myOldBranchList)
   .Dump("skimmedDataset.root",myBranchListForSkimming)
   .Histo("myNewBranch");
```

This tree must contain the entries which passed the filters, if any, and the "pseudo-branches" if any and selected for the skimming. The return value must expose the TDataFrameInterface in order to be able to continue the chain of actions/filters.

Dump shall also be a synchronisation point, i.e. implicitly triggering Run.

**Comment by eguiraud** [comment]
other possible names: `Snapshot`, `Freeze`.

**Comment by dpiparo** [comment]
I think Snpshot is my favourite since Freeze might have a negative connotation.

**Comment by Axel-Naumann** [comment]
`Tee()`? Or is that too geeky? :-)

**Comment by dpiparo** [comment]
It *is* geeky but I like it since there is a perfect analogy with the famous command. I wonder if the name implies some *nix a priory knowledge and is not neglecting our Windows community though.

**Comment by eguiraud** [comment]
So far we have:
- Dump
- Snapshot
- Freeze
- Tee
- Checkpoint

I personally favor `Snapshot`, `Checkpoint` or `Tee` because I think they make it very very clear that they save the state of the data at that point of the functional chain and at the same time you can keep working as if nothing had happened.

**Comment by dpiparo** [comment]
Hi,

Nice summary!
my list, in order of preference would be
- Snapshot
- Tee
- Checkpoint
- Dump

**Comment by Axel-Naumann** [comment]
For me, checkpointing (as well as snapshotting, but less so) implies that the dump can be revived, i.e. I can  resume the subsequent steps from the checkpoint. See https://www.wikiwand.com/en/Application_checkpointing

That doesn't seem to be the case here, right? So my favorites are `Dump()` (but that sounds like a dead end) and `Tee()`.

**Comment by eguiraud** [comment]
You can certainly resume your work from the checkpoint/snapshot: the call writes a new `TTree` to disk, with all filters applied and the quantities created via `AddBranch` added to it. At a later time you can construct a data-frame from that new tree and effectively resume your work from the checkpoint.

The call returns a new `TDataFrame` that reads from this new `TTree`, so you can also keep working on the chain right after the call to "`Dump`"

**Comment by eguiraud** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Snapshot action](https://trello.com/c/aNYA7cia/6-snapshot-action)

**Comment by eguiraud** [comment]
done in ROOT
