### ISSUE TITLE
Compare the scaling and runtime performance of the TDataFrame with other data processing helpers of ROOT

### ISSUE THREAD

**Issue by dpiparo** [bluehood/tdataframe#39]
Examples are:
- TProcessExecutor
- Proof(Lite)
- TTreeDraw

Writing a battery of tests involving a realistic or at least complex usecase can help spotting regressions and hotspots to mitigate in the current implementation.

**Comment by dpiparo** [comment]
A first step towards this testing has been made with this benchmark: https://github.com/bluehood/tdataframe/blob/master/benchmarks/benchmark.cxx

**Comment by eguiraud** [comment]
While serious benchmarking and consequent bottleneck optimization of TDF remains on my to-do list, there have been comparisons with TTree::Draw and other legacy analysis code. Closing.
