### ISSUE TITLE
Refactor the code in several headers

### ISSUE THREAD

**Issue by dpiparo** [bluehood/tdataframe#40]
The "one header solution" works well, but for the sake of tidiness, one can opt for a refactoring of the code which foresees the distribution of the code in several headers. For example sealing the ancillary classes such as the TActionResultPtr or again the "meta-utils" in a different file. For the latter the idea of "core/foundation" could be followed.

**Comment by eguiraud** [comment]
At the same time, it is highly desirable that users will ever only have to include `TDataFrame.hxx` to use the framework. I am on this.

**Comment by eguiraud** [comment]
done in ROOT
