### ISSUE TITLE
Implement actions for multidimensional histograms

### ISSUE THREAD

**Issue by dpiparo** [bluehood/tdataframe#41]
The title says it all. Probably their name should be Histo2D and Histo3D.

**Comment by eguiraud** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Histo actions for TH2F and TH3F](https://trello.com/c/BKxHBRhf/33-histo-actions-for-th2f-and-th3f)

**Comment by eguiraud** [comment]
done in ROOT
