### ISSUE TITLE
After a call to TDataFrame::Run, references to chain states are dangling

### ISSUE THREAD

**Issue by eguiraud** [bluehood/tdataframe#42]
After executing the following code:
```c++
TDataFrame d(treeName, filePtr, branchList);
auto& f = d.Filter(myFilter);
auto h = f.Histo();
h->Draw(); // Run is called here, when accessing the histogram for the first time
```
`f` is a dangling reference.

**Proposed solution:**
1. `TDataFrame` should not forget filters and branches after running, only executed actions and smart pointers to their results.
2. `Filter` and `AddBranch` should return a wrapper object (a proxy) that only exposes the `TDataFrameInterface` methods.

**Comment by dpiparo** [comment]
The filters/branches should keep track of the proxies they issued. This information can be used to know if the events passing the filter shall be cached. Indeed actions "hang" from filters/branches.

**Comment by Axel-Naumann** [comment]
I vote for the latter - a `TDataFrameActionRef` or similar - which allows us to get rid of the `&` in the `auto`, i.e. `auto f = d.Filter(f)`.

**Comment by dpiparo** [comment]
As a side note, I'd like to add that an overloadable "." operator would 
make this job even easier :)

**Comment by eguiraud** [comment]
@karies we have to do both 1. and 2. to make this work nicely :)

**Comment by Axel-Naumann** [comment]
@bluehood not necessarily: if the `TDataFrameActionRef` is actually a `TDataFrameActionRef` then users have to use `op ->` and the "pointer" can be `nullptr` once the `TDataFrame` has discarded the action.

**Comment by Axel-Naumann** [comment]
http://open-std.org/JTC1/SC22/WG21/docs/papers/2016/p0416r1.pdf

I doubt it'll happen in 17, though.

**Comment by eguiraud** [comment]
fixed in master
