### ISSUE TITLE
Caching results of filters across different event-loops

### ISSUE THREAD

**Issue by eguiraud** [bluehood/tdataframe#43]
Once issue #42 will be solved, filters can be reused for different runs.
It would be nice if they cached the results of the first run.

**Comment by dpiparo** [comment]
The filter method shall also receive a parameter to allow disabling of caching, which should be on by default.

**Comment by eguiraud** [comment]
Nice-to-have, but `Cache` has sufficient overlap with this feature to make it a "won't fix"
