### ISSUE TITLE
Provide a way to run over subranges of a certain dataset

### ISSUE THREAD

**Issue by dpiparo** [bluehood/tdataframe#46]
It is pretty common to decide to run on a subset of a certain dataset, on a certain range of entries for example.
A range class shall be developed which has the following features:
- It has a begin and an end entry number as well as a stride value.
- It is constructible with an initialiser list
- It can be passed to actions

Actions which are "ranged" are "instant": they run immediately together with all the other actions with an identical (or contained?) range. 
In first approximation, if a filter cached the entries numbers which passed for a range and a different range is used for a second run, the list is scratched. In second approximation, one can check if the second range is strictly included in the previous range or again the filter can be run only for the entries outside the previous range if this last one does not include the new one.

**Comment by Axel-Naumann** [comment]
It should also convert to and from a TEntryList, and possibly
serializable into a ROOT file.

**Comment by dpiparo** [comment]
Good point. This plays out nicely with another idea, i.e. an action, say EntryList(), which returns a TEntryList relative to the entries passing through the cutflow, e.g.:
`auto myEntryList = myDF.Filter(filterFunction1).Filter(filterFunction2).AddBranch("newColumn", ProduceNewColumn, colList).EntryList()`

**Comment by eguiraud** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Action ranges](https://trello.com/c/7dEwdfYB/7-action-ranges)

**Comment by eguiraud** [comment]
This idea has been played with and modified many times.

A `Range` transformation that allows to process only certain entries and provides a mechanism for early quitting of the event loop is ready for inclusion in ROOT.

It does not support multi-threading (an exception is thrown if `Range` is called and `EnableImplicitMT` has been previously called). It does not support `TEntryLists`, as facilities for reading and writing `TEntryLists` with `TDataFrame` will be provided separately.

**Comment by dpiparo** [comment]
Hi,

I wonder if the exception is a bit too strong and a warning would not be more appropriate in this case...

**Comment by eguiraud** [comment]
I suppose what you are suggesting is to print a warning and let the code act as if the call to Range had not been made. I thought about this, and my conclusion was that it would have impacted the inner logic more than it would have benefited users: upon seeing the warning, 9 out of 10 times you would want to terminate the execution of the analysis anyway, because it's not doing what you where expecting. In that other case out of ten...you probably missed the warning and think the code is doing something different than what it actually is.

If you do not agree this is not a decision set in stone obviously.

**Comment by dpiparo** [comment]
Hi,
exactly. Actually your argument is a good one.

**Comment by Axel-Naumann** [comment]
If I say "Range" and it's not respected then the result is going to be wrong. That's worth an exception. (People ignore warnings.)
