### ISSUE TITLE
write a user guide

### ISSUE THREAD

**Issue by eguiraud** [bluehood/tdataframe#49]
Pluggable in the doxygen docs or usable as a standalone document.

**Comment by eguiraud** [comment]
the work-in-progress can be found [here](https://gist.github.com/bluehood/c05a97085e47f71505297b3786337475).

**Comment by dpiparo** [comment]
Nice document. Why not making it part of the repository directly? A comment: perhaps using the most naive markdown possible might be a good strategy as the text can be inserted in other contexts, e.g. Doxygen comments.

**Comment by eguiraud** [comment]
good points. I'll open a PR to allow review of the guide as soon as I have a first version, and I plan to make it doxygen-compatible (it's just that the emoji autocompletion on github is so easy to use :) )

**Comment by eguiraud** [comment]
done: see PR #59
