### ISSUE TITLE
AddBranch should check if a branch with the new name already exists

### ISSUE THREAD

**Issue by dpiparo** [bluehood/tdataframe#51]
Currently AddBranch does not check if a branch with the required name exists already. The user should be informed if this situation occurs.

**Comment by eguiraud** [comment]
Yes, currently using the same name of an existing branch overrides it.
Related: there is no check for consistency between the type returned by the `AddBranch` lambda and the type of the corresponding argument in filter or action lambdas that use that temporary branch.
A runtime check can be performed using `TDataFrameBranch::GetTypeID`.

**Comment by eguiraud** [comment]
I would rather print a warning than throw an exception in case the branch name already exists.
What do others think?

**Comment by Axel-Naumann** [comment]
I vote for exception: this can give wrong results if ignored - think of an existing branch with same type (say `vector<double>`) but different value. Not unlikely...

**Comment by dpiparo** [comment]
I vote for exception too: we have another case where we throw, i.e. when acting on filters/branches when the original DF is out of scope. I see an analogy even if in this latter case the result would be a nasty segfault :)

**Comment by eguiraud** [comment]
exception it is.

fixed in commit 847729f.
