### ISSUE TITLE
Optimise memory usage of parallel histogramming

### ISSUE THREAD

**Issue by dpiparo** [bluehood/tdataframe#57]
If the user specified a min and a max range for the output histogram, we can directly use a `TThreadedObject<TH1F>` therewith avoiding to cache too many values in memory.
From the point of view of the implementation, this can be achieved with a different `FillOperation`, say `FillOperationTO`: the right operation can be selected when creating the lambda for the action (the signature will be of course the same).

**Comment by eguiraud** [comment]
@dpiparo this is done, correct?

**Comment by dpiparo** [comment]
Absolutely: sorry for not closing this.
