### ISSUE TITLE
FilterNot

### ISSUE THREAD

**Issue by eguiraud** [bluehood/tdataframe#58]
...or similar names :)

Currently there is no easy way to invert the result of a filter function. This results in unnecessary duplication of code:

```c++
auto isPos = [](int x) { return x > 0; };
auto isNeg = [](int x) { return x < 0; };
// alternatively [](int x) { return !isPos(x); }, but still not nice
d.Filter(isPos).Count();
d.Filter(isNeg).Count();
```

We could simply introduce a `FilterNot` function, as @karies suggested some time ago.
I think it would be even better to let the user write something like `Filter(!myCut)` but I do not see any way we can make that work.

**Comment by dpiparo** [comment]
Hi,

very nice idea. 
Can we get out of it with a template function/functor (`Negate`) which has the same signature of the filter and returns the negation of it?
```C++
auto isPos = [](int x) { return x > 0; };
auto isNeg = [](int x) { return x < 0; };
// alternatively [](int x) { return !isPos(x); }, but still not nice
d.Filter(isPos).Count();
d.Filter(Negate(isPos)).Count();
```

**Comment by dpiparo** [comment]
It seems others thought about this too: http://www.open-std.org/JTC1/SC22/WG21/docs/papers/2015/p0005r0.html

**Comment by dpiparo** [comment]
So, this can be solved (http://stackoverflow.com/questions/34330300/why-are-there-stdnot1-and-stdnot2-rather-than-a-single-overloaded-stdn):
```
~> cat not.h 

bool filter ( int i ) { return i > 3;}

template <typename Pred>
class not_fn_t {
    typename std::decay<Pred>::type pred;
public:
    explicit not_fn_t(Pred p): pred(p) {}
    template <typename... A>
    bool operator()(A&&... a) const {
        return !this->pred(std::forward<A>(a)...);
    }
};
template <typename Pred>
not_fn_t<Pred> not_fn(Pred&& pred) {
    return not_fn_t<Pred>(std::forward<Pred>(pred));
}
-> ~/not_fn root -l
root [0] #include "not.h"
root [1] filter(5)
(bool) true
root [2] a = not_fn(filter)
(not_fn_t<bool (&)(int)> &) @0x10821e6a0
root [3] a(5)
(bool) false
```

**Comment by eguiraud** [comment]
great, thank you! this is it

it looks like `std::not_fn` actually made it in c++17, but for now I guess we'll have to implement it ourselves.
how do we actually want users to call it?

```c++
ROOT::TDataFrame d(...);
d.Filter(ROOT::NotFn(cut));
// or
d.Filter(ROOT::DataFrame::NotFn(cut)); // we do not have a ROOT::DataFrame namespace atm
// or
d.Filter(ROOT::Details::NotFn(cut));
// or?
```

**Comment by eguiraud** [comment]
This will solve itself in ROOT when we'll backport `std::not_fn`. Closing.
