### ISSUE TITLE
improvements to run-time type guessing mechanism

### ISSUE THREAD

**Issue by eguiraud** [bluehood/tdataframe#65]
The current type guessing mechanism has two issues:
- type guessing is performed even when the branch type is explicitly specified by users as a template parameter to the action
- it does not throw in case the type could not be guessed (in this case `TTreeReaderValue` aborts execution upon reading of the first entry)

Snippet to reproduce both behaviours:
```c++
#include "TDataFrame.hxx"
#include "TString.h"

int main() {
   {
      TFile f("myfile.root", "RECREATE");
      TTree t("myTree", "myTree");
      int b = 42;
      t.Branch("b", &b);
      TString s = "fortytwo";
      t.Branch("s", &s);
      t.Fill();
      t.Write();
   }
   
   TFile f("myfile.root");
   ROOT::TDataFrame d("myTree", &f);
   // this should cause a type mismatch in the TTreeReaderValue but it doesn't
   // because type guessing is done even if types are specified
   // (not sure if bug or feature)
   auto hb = d.Histo<double>("b");
   // this should throw at this point because `TString` cannot be guessed...
   auto hs = d.Histo("s");
   // ...instead TTreeReaderValue aborts execution at this line
   *hs;

   return 0;
}
```

**Comment by dpiparo** [comment]
Hi,

perhaps this can be solved as discussed introducing a fake type with a suggestive name used by default rather than `double`, e.g. `TDFUknownBranchType`.

**Comment by eguiraud** [comment]
yes, definitely!

**Comment by eguiraud** [comment]
done in ROOT
