### ISSUE TITLE
Improve the TActionResultPtr

### ISSUE THREAD

**Issue by dpiparo** [bluehood/tdataframe#69]
Three ideas to improve the TActionResultPtr<T>:
1. Call the template TActionResult<T> and not TActionResultPtr<T>
2. Add the begin and end methods to it conditionally, issue static asserts if T is not a container
3. Remove the Get and GetUnchecked methods, which the user does not need to invoke

**Comment by eguiraud** [comment]
Hi,
I think 2. and 3. are good ideas, and with 2. and 3. done of course that object is less of a `Ptr` than before.

I wonder if we could maintain a name that conveys the idea that `TActionResult` is not the result itself, but a proxy to it (e.g. one has to use `->` and `*` to access the actual result). But maybe I'm overthinking, and documenting this fact is enough.

**Comment by dpiparo** [comment]
`TActionResultProxy` ? `TActionResultValue` (like `TTreeReaderValue`)?

**Comment by eguiraud** [comment]
dammit I started reading that like a ternary logic operator xD

I like `TActionResultProxy` because it is exactly what it is.

**Comment by dpiparo** [comment]
I buy it!

**Comment by eguiraud** [comment]
alright, so:

- [x] `TActionResultPtr` -> `TActionResultProxy`
- [x] SFINAE `begin()` and `end()`, activated if the proxied result is a container
- [x] remove `Get` and `GetUnchecked` (and their usage inside tests and such)

**Comment by dpiparo** [comment]
Exactly. I can take care of that. Is master a good branch?

**Comment by eguiraud** [comment]
yep, I believe so

**Comment by eguiraud** [comment]
done in #73
