### ISSUE TITLE
Illustrate code as notebook in SWAN

### ISSUE THREAD

**Issue by dpiparo** [bluehood/tdataframe#7]
It would be nice to make the code available with a single click in SWAN, perhaps providing an index notebook and several other ones showing the features of the functional chain based analysis. A possible approach could even be to write examples as ROOT macros and provide a "driver notebook" that converts them in notebooks with the converttonotebook.py script (https://root.cern.ch/gitweb/?p=root.git;a=blob;f=documentation/doxygen/converttonotebook.py;h=3b3f6e501e918a68f3cbb916744d1aa629b1c441;hb=HEAD)
The macros could be the future root tutorials about TDataFrame in any case.

**Comment by eguiraud** [comment]
done in pull request #8.
